{{- if and .Values.decode.create .Values.multinode }}
apiVersion: leaderworkerset.x-k8s.io/v1
kind: LeaderWorkerSet
metadata:
  name: {{ include "llm-d-modelservice.decodeName" . }}
  labels:
    {{- include "llm-d-modelservice.labels" . | nindent 4 }}
    {{- include "llm-d-modelservice.decodelabels" . | nindent 4 }}
  {{- if or .Values.decode.subGroupExclusiveTopology .Values.decode.annotations }}
  annotations:
  {{- if .Values.decode.subGroupExclusiveTopology }}
    leaderworkerset.sigs.k8s.io/subgroup-exclusive-topology: kubernetes.io/hostname
  {{- end }}
  {{- if .Values.decode.annotations }}
    {{ toYaml .Values.decode.annotations | nindent 4 }}
    {{- end }}
  {{- end }}
spec:
  {{- if not .Values.decode.autoscaling.enabled }}
  replicas: {{ ternary .Values.decode.replicas 1 (hasKey .Values.decode "replicas") }}
  {{- end }}
  leaderWorkerTemplate:
    size: {{ int (include "llm-d-modelservice.dataParallelism" .Values.decode.parallelism) }}
    {{- if .Values.decode.subGroupPolicy }}
    subGroupPolicy:
    {{- toYaml .Values.decode.subGroupPolicy | nindent 6 }}
    {{-  end }}
    workerTemplate:
      metadata:
        labels:
          {{- include "llm-d-modelservice.decodelabels" . | nindent 10 }}
        {{- if or .Values.decode.subGroupExclusiveTopology .Values.decode.annotations }}
        annotations:
        {{- if .Values.decode.subGroupExclusiveTopology }}
          leaderworkerset.sigs.k8s.io/subgroup-exclusive-topology: kubernetes.io/hostname
        {{- end }}
        {{- if .Values.decode.annotations }}
          {{ toYaml .Values.decode.annotations | nindent 10 }}
          {{- end }}
        {{- end }}
      spec:
        {{- if hasKey .Values.decode "hostIPC" }}
        hostIPC: {{ .Values.decode.hostIPC }}
        {{- end }}
        {{- if hasKey .Values.decode "hostPID" }}
        hostPID: {{ .Values.decode.hostPID }}
        {{- end }}
        {{- with .Values.routing }}
        {{ (include "llm-d-modelservice.routingProxy" (dict "routing" . "Values" $.Values)) | nindent 8 }}
        {{- end }}
        {{- (include "llm-d-modelservice.modelPod" (dict "pdSpec" .Values.decode "Values" .Values "Release" .Release "Chart" .Chart)) | nindent 6 }}
        {{- with .Values.decode.containers }}
        containers:
          {{- range . }}
        {{- (include "llm-d-modelservice.container" (dict "role" "decode" "container" . "parallelism" $.Values.decode.parallelism "Values" $.Values "Release" $.Release "Chart" $.Chart)) | nindent 8 }}
          {{- end }}
        {{- end }}
        {{- if .Values.decode.tolerations }}
        tolerations:
          {{- toYaml .Values.decode.tolerations | nindent 10 }}
        {{- end }}
{{- end }}
