{{- if .Values.routing.epp.create -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "llm-d-modelservice.eppName" . }}
  labels:
    llm-d.ai/epp: {{ include "llm-d-modelservice.eppName" . }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ default 1 .Values.routing.epp.replicas }}
  selector:
    matchLabels:
      llm-d.ai/epp: {{ include "llm-d-modelservice.eppName" . }}
  template:
    metadata:
      labels:
        llm-d.ai/epp: {{ include "llm-d-modelservice.eppName" . }}
    spec:
      containers:
      - name: epp
        imagePullPolicy: Always
        image: {{ required "routing.epp.image must be specified" .Values.routing.epp.image }}
        args:
        - --poolName
        - {{ include "llm-d-modelservice.inferencePoolName" . }}
        - --poolNamespace
        - {{ .Release.Namespace }}
        - -v
        - "{{ default 4 .Values.routing.epp.debugLevel }}"
        - --zap-encoder
        - json
        - --grpcPort
        - "9002"
        - --grpcHealthPort
        - "9003"
        {{- if .Values.routing.epp.pluginsConfigFile }}
        - "-configFile"
        - "config/{{ .Values.routing.epp.pluginsConfigFile }}"
        {{- end}}
        env:
        {{- if .Values.tracing.enabled }}
        {{- if .Values.tracing.components.eppInferenceScheduler }}
        - name: OTEL_TRACING_ENABLED
          value: "true"
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: {{ .Values.tracing.otelCollectorEndpoint | quote }}
        - name: OTEL_SAMPLING_RATE
          value: {{ .Values.tracing.samplingRate | quote }}
        {{- if .Values.tracing.apiToken }}
        - name: OTEL_EXPORTER_OTLP_HEADERS
          value: "authorization=Bearer {{ .Values.tracing.apiToken }}"
        {{- end }}
        {{- else }}
        - name: OTEL_TRACING_ENABLED
          value: "false"
        {{- end }}
        {{- else }}
        - name: OTEL_TRACING_ENABLED
          value: "false"
        {{- end }}
        {{- with .Values.routing.epp.env }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        ports:
        - containerPort: 9002
          name: grpc
          protocol: TCP
        - containerPort: 9003
          name: grpc-health
          protocol: TCP
        - containerPort: 9090
          name: metrics
          protocol: TCP
        {{- with .Values.routing.epp.extraContainerPorts }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- if (not .Values.routing.epp.disableReadinessProbe) }}
        readinessProbe:
          grpc:
            port: 9003
            service: envoy.service.ext_proc.v3.ExternalProcessor
          initialDelaySeconds: 5
          timeoutSeconds: 1
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
        {{- end }}
        {{- if (not .Values.routing.epp.disableLivenessProbe) }}
        livenessProbe:
          grpc:
            port: 9003
            service: envoy.service.ext_proc.v3.ExternalProcessor
          initialDelaySeconds: 5
          timeoutSeconds: 1
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
        {{- end }}
      {{- if .Values.routing.epp.pluginsConfigFile }}
        volumeMounts:
          - name: plugins-config-volume
            mountPath: "/config"
      volumes:
      - name: plugins-config-volume
        configMap:
          name: {{ include "llm-d-modelservice.eppConfigName" . }}
      {{- end }}
      serviceAccount: {{ include "llm-d-modelservice.eppServiceAccountName" . }}
      serviceAccountName: {{ include "llm-d-modelservice.eppServiceAccountName" . }}
{{- end }}
